export const montrealStarQuestions = [
  {
    montrealStarQuestion: 'Ruby Slippers, Judy Garland',
    montrealStarOptions: [26, 22, 28, 30, 29],
    montrealStarAnswer: 28,
    montrealStarCloseAnswers: [30, 29, 26],
    montrealStarFact: 'This item was sold at auction for $28 million.',
    montrealStarImage: require('../../assets/images/montrealgmpph.png'),
  },
  {
    montrealStarQuestion: 'World Series Jersey (1932), Babe Ruth',
    montrealStarOptions: [21, 22, 24, 26, 27],
    montrealStarAnswer: 24.1,
    montrealStarCloseAnswers: [22, 26, 27],
    montrealStarFact: 'This item was sold at auction for $24.1 million.',
    montrealStarImage: require('../../assets/images/montrealgmpph2.png'),
  },
  {
    montrealStarQuestion: 'Rolex Daytona (personal), Paul Newman',
    montrealStarOptions: [16, 17.8, 18, 19, 20],
    montrealStarAnswer: 17.8,
    montrealStarCloseAnswers: [16, 18, 19],
    montrealStarFact: 'This item was sold at auction for $17.8 million.',
    montrealStarImage: require('../../assets/images/montrealgmpph3.png'),
  },
  {
    montrealStarQuestion: '1998 NBA Finals Jersey, Michael Jordan',
    montrealStarOptions: [9, 10.1, 10, 11, 12],
    montrealStarAnswer: 10.1,
    montrealStarCloseAnswers: [9, 10, 11],
    montrealStarFact: 'This item was sold at auction for $10.1 million.',
    montrealStarImage: require('../../assets/images/montrealgmpph4.png'),
  },
  {
    montrealStarQuestion: '“Hand of God” Jersey (1986), Diego Maradona',
    montrealStarOptions: [8, 9.3, 9, 10, 11],
    montrealStarAnswer: 9.3,
    montrealStarCloseAnswers: [8, 9, 10],
    montrealStarFact: 'This item was sold at auction for $9.3 million.',
    montrealStarImage: require('../../assets/images/montrealgmpph5.png'),
  },
  {
    montrealStarQuestion:
      'Elizabeth Taylor Diamond (33.19 ct), Elizabeth Taylor',
    montrealStarOptions: [8, 8.8, 9, 10, 11],
    montrealStarAnswer: 8.8,
    montrealStarCloseAnswers: [8, 9, 10],
    montrealStarFact: 'This item was sold at auction for $8.8 million.',
    montrealStarImage: require('../../assets/images/montrealgmpph6.png'),
  },
  {
    montrealStarQuestion: 'Martin D-18E (MTV Unplugged), Kurt Cobain',
    montrealStarOptions: [5, 6, 7, 8, 9],
    montrealStarAnswer: 6,
    montrealStarCloseAnswers: [5, 7, 8],
    montrealStarFact: 'This item was sold at auction for $6 million.',
    montrealStarImage: require('../../assets/images/montrealgmpph7.png'),
  },
  {
    montrealStarQuestion: 'New York Yankees Jersey (1928–1930), Babe Ruth',
    montrealStarOptions: [5, 5.64, 6, 7, 8],
    montrealStarAnswer: 5.64,
    montrealStarCloseAnswers: [5, 6, 7],
    montrealStarFact: 'This item was sold at auction for $5.64 million.',
    montrealStarImage: require('../../assets/images/montrealgmpph8.png'),
  },
  {
    montrealStarQuestion: 'White Dress, The Seven Year Itch, Marilyn Monroe',
    montrealStarOptions: [5, 5.6, 6, 7, 8],
    montrealStarAnswer: 5.6,
    montrealStarCloseAnswers: [5, 6, 7],
    montrealStarFact: 'This item was sold at auction for $5.6 million.',
    montrealStarImage: require('../../assets/images/montrealgmpph9.png'),
  },
  {
    montrealStarQuestion: 'Rolex GMT-Master, Marlon Brando',
    montrealStarOptions: [4, 5, 5.1, 6, 7],
    montrealStarAnswer: 5.1,
    montrealStarCloseAnswers: [5, 6, 7],
    montrealStarFact: 'This item was sold at auction for $5.1 million.',
    montrealStarImage: require('../../assets/images/montrealgmpph10.png'),
  },
  {
    montrealStarQuestion:
      '“Happy Birthday, Mr. President” Dress, Marilyn Monroe',
    montrealStarOptions: [4, 4.8, 5, 6, 7],
    montrealStarAnswer: 4.8,
    montrealStarCloseAnswers: [4, 5, 6],
    montrealStarFact: 'This item was sold at auction for $4.8 million.',
    montrealStarImage: require('../../assets/images/montrealgmpph11.png'),
  },
  {
    montrealStarQuestion: 'Dress from My Fair Lady, Audrey Hepburn',
    montrealStarOptions: [4, 4.5, 5, 6, 7],
    montrealStarAnswer: 4.5,
    montrealStarCloseAnswers: [4, 5, 6],
    montrealStarFact: 'This item was sold at auction for $4.5 million.',
    montrealStarImage: require('../../assets/images/montrealgmpph12.png'),
  },
  {
    montrealStarQuestion: 'Blue Fender Mustang, Kurt Cobain',
    montrealStarOptions: [4, 4.5, 5, 6, 7],
    montrealStarAnswer: 4.5,
    montrealStarCloseAnswers: [4, 5, 6],
    montrealStarFact: 'This item was sold at auction for $4.5 million.',
    montrealStarImage: require('../../assets/images/montrealgmpph13.png'),
  },
  {
    montrealStarQuestion: 'Mike Todd Tiara, Elizabeth Taylor',
    montrealStarOptions: [4, 4.2, 5, 6, 7],
    montrealStarAnswer: 4.2,
    montrealStarCloseAnswers: [4, 5, 6],
    montrealStarFact: 'This item was sold at auction for $4.2 million.',
    montrealStarImage: require('../../assets/images/montrealgmpph14.png'),
  },
  {
    montrealStarQuestion:
      '“The Black Strat” (Fender Stratocaster), David Gilmour',
    montrealStarOptions: [3, 3.95, 4, 5, 6],
    montrealStarAnswer: 3.95,
    montrealStarCloseAnswers: [4, 5, 6],
    montrealStarFact: 'This item was sold at auction for $3.95 million.',
    montrealStarImage: require('../../assets/images/montrealgmpph15.png'),
  },
  {
    montrealStarQuestion: 'Two Kramer Guitars, Eddie Van Halen',
    montrealStarOptions: [3, 3.93, 4, 5, 6],
    montrealStarAnswer: 3.93,
    montrealStarCloseAnswers: [3, 4, 5],
    montrealStarFact: 'This item was sold at auction for $3.93 million.',
    montrealStarImage: require('../../assets/images/montrealgmpph16.png'),
  },
  {
    montrealStarQuestion: '70th Home Run Baseball, Mark McGwire',
    montrealStarOptions: [2, 2.5, 3, 3.5, 4],
    montrealStarAnswer: 3,
    montrealStarCloseAnswers: [2.5, 3.5, 4],
    montrealStarFact: 'This item was sold at auction for $3 million.',
    montrealStarImage: require('../../assets/images/montrealgmpph17.png'),
  },
  {
    montrealStarQuestion:
      'Wicked Witch of the West Hat (The Wizard of Oz), Margaret Hamilton',
    montrealStarOptions: [2, 2.5, 2.93, 3, 3.5],
    montrealStarAnswer: 2.93,
    montrealStarCloseAnswers: [2.5, 3, 3.5],
    montrealStarFact: 'This item was sold at auction for $2.93 million.',
    montrealStarImage: require('../../assets/images/montrealgmpph18.png'),
  },
  {
    montrealStarQuestion: 'Framus Hootenanny Guitar, John Lennon',
    montrealStarOptions: [2, 2.5, 2.85, 3, 3.5],
    montrealStarAnswer: 2.85,
    montrealStarCloseAnswers: [2.5, 3, 3.5],
    montrealStarFact: 'This item was sold at auction for $2.85 million.',
    montrealStarImage: require('../../assets/images/montrealgmpph19.png'),
  },
  {
    montrealStarQuestion: 'Gibson J-160E Guitar, John Lennon',
    montrealStarOptions: [2, 2.4, 2.5, 3, 3.5],
    montrealStarAnswer: 2.4,
    montrealStarCloseAnswers: [2, 2.5, 3],
    montrealStarFact: 'This item was sold at auction for $2.4 million.',
    montrealStarImage: require('../../assets/images/montrealgmpph20.png'),
  },
  {
    montrealStarQuestion:
      'Bass Drum Head with Logo (from Sgt. Pepper cover), The Beatles',
    montrealStarOptions: [1.5, 2, 2.1, 2.5, 3],
    montrealStarAnswer: 2.1,
    montrealStarCloseAnswers: [2, 2.5, 3],
    montrealStarFact: 'This item was sold at auction for $2.1 million.',
    montrealStarImage: require('../../assets/images/montrealgmpph21.png'),
  },
  {
    montrealStarQuestion: '“Like a Rolling Stone” Manuscript, Bob Dylan',
    montrealStarOptions: [1.5, 2, 2.045, 2.5, 3],
    montrealStarAnswer: 2.045,
    montrealStarCloseAnswers: [2, 2.5, 3],
    montrealStarFact: 'This item was sold at auction for $2.045 million.',
    montrealStarImage: require('../../assets/images/montrealgmpph22.png'),
  },
  {
    montrealStarQuestion: '“Wolf” Guitar, Jerry Garcia',
    montrealStarOptions: [1.5, 1.9, 2, 2.5, 3],
    montrealStarAnswer: 1.9,
    montrealStarCloseAnswers: [1.5, 2, 2.5],
    montrealStarFact: 'This item was sold at auction for $1.9 million.',
    montrealStarImage: require('../../assets/images/montrealgmpph23.png'),
  },
  {
    montrealStarQuestion: '“Thriller” Jacket, Michael Jackson',
    montrealStarOptions: [1, 1.5, 1.8, 2, 2.5],
    montrealStarAnswer: 1.8,
    montrealStarCloseAnswers: [1.5, 2, 2.5],
    montrealStarFact: 'This item was sold at auction for $1.8 million.',
    montrealStarImage: require('../../assets/images/montrealgmpph24.png'),
  },
  {
    montrealStarQuestion: '1954 Fender Stratocaster, David Gilmour',
    montrealStarOptions: [1, 1.5, 1.8, 2, 2.5],
    montrealStarAnswer: 1.8,
    montrealStarCloseAnswers: [1.5, 2, 2.5],
    montrealStarFact: 'This item was sold at auction for $1.8 million.',
    montrealStarImage: require('../../assets/images/montrealgmpph25.png'),
  },
  {
    montrealStarQuestion: 'Engagement Ring, Barbara Sinatra',
    montrealStarOptions: [1, 1.5, 1.7, 2, 2.5],
    montrealStarAnswer: 1.7,
    montrealStarCloseAnswers: [1.5, 2, 2.5],
    montrealStarFact: 'This item was sold at auction for $1.7 million.',
    montrealStarImage: require('../../assets/images/montrealgmpph26.png'),
  },
  {
    montrealStarQuestion: 'Rolex “Crazy Doc,” Eric Clapton',
    montrealStarOptions: [1, 1.5, 1.6, 2, 2.5],
    montrealStarAnswer: 1.6,
    montrealStarCloseAnswers: [1.5, 2, 2.5],
    montrealStarFact: 'This item was sold at auction for $1.6 million.',
    montrealStarImage: require('../../assets/images/montrealgmpph27.png'),
  },
  {
    montrealStarQuestion: 'Dress from The Wizard of Oz, Judy Garland',
    montrealStarOptions: [1, 1.5, 1.56, 2, 2.5],
    montrealStarAnswer: 1.56,
    montrealStarCloseAnswers: [1.5, 2, 2.5],
    montrealStarFact: 'This item was sold at auction for $1.56 million.',
    montrealStarImage: require('../../assets/images/montrealgmpph28.png'),
  },
  {
    montrealStarQuestion: 'Sky Stang 1 (1993 Fender Mustang), Kurt Cobain',
    montrealStarOptions: [1, 1.5, 1.58, 2, 2.5],
    montrealStarAnswer: 1.58,
    montrealStarCloseAnswers: [1.5, 2, 2.5],
    montrealStarFact: 'This item was sold at auction for $1.58 million.',
    montrealStarImage: require('../../assets/images/montrealgmpph29.png'),
  },
  {
    montrealStarQuestion: 'Lightsaber (screen-used, Star Wars), Obi-Wan Kenobi',
    montrealStarOptions: [1, 1.3, 1.5, 2, 2.5],
    montrealStarAnswer: 1.3,
    montrealStarCloseAnswers: [1.5, 2, 2.5],
    montrealStarFact: 'This item was sold at auction for $1.3 million.',
    montrealStarImage: require('../../assets/images/montrealgmpph30.png'),
  },
];
